import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Image from "next/image"; // 1. Importujemy komponent Image
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col p-8">
        {/* Kontener div otaczający nagłówek z dodanym obrazkiem po lewej stronie */}
        <div className="flex items-center gap-4"> 
          <Image 
            src="/avocado.jpg" 
            alt="Avocado" 
            width={100} 
            height={100}
            className="object-cover rounded-md"
          />
          <h1 className="mb-4 text-4xl font-bold tracking-tight">
            Next.js CRUD App
          </h1>
        </div>
        <hr />
        <p>&nbsp;</p>

        {/* Treść stron aplikacji */}
        {children}
      </body>
    </html>
  );
}